name: EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "EAS Build Profile"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - production
      platform:
        description: "Plattform"
        required: true
        default: "android"
        type: choice
        options:
          - android
          - ios
          - all

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run EAS Build
        run: eas build --platform "${{ github.event.inputs.platform }}" --profile "${{ github.event.inputs.profile }}" --non-interactive --wait
